---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'


platforms:
  #- name: ubuntu-12.04
  - name: ubuntu-14.04
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    run_list:
      - recipe[timezone-ii]
      - recipe[ubuntu-change-source-list]
      - recipe[apt]
    attributes:
      java:
        install_flavor: "openjdk"
        jdk_version: 7
      apt:
        compile_time_update: true
      build-essential:
        compile_time: true
      ubuntu:
        mirror_site_url: "http://ftp.jaist.ac.jp/pub/Linux/ubuntu/"
        version: "14.04"
        need_deb_src: false
        need_update: true

  - name: centos-7.0
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    run_list:
      - recipe[yum]
    attributes:
      java:
        install_flavor: "openjdk"
        jdk_version: 7
      yum:
        main:
          keepcache:  True

suites:
  - name: default
    run_list:
      - recipe[timezone-ii]
      - recipe[java]
      - recipe[build-essential]
      - recipe[r-compiledfromsource]
    attributes:
      tz: "Asia/Tokyo"
