---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'


platforms:
  #- name: ubuntu-12.04
  - name: ubuntu-14.04
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    run_list:
      - recipe[timezone-ii]
      - recipe[r-compiledfromsource::change-apt]
    attributes:
      java:
        install_flavor: "openjdk"
        jdk_version: 7
      build-essential:
        compile_time: true

  - name: centos-7.0
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    run_list:
      - recipe[yum]
    attributes:
      java:
        install_flavor: "openjdk"
        jdk_version: 7
      yum:
        main:
          keepcache:  True

suites:
  - name: default
    run_list:
      - recipe[timezone-ii]
      - recipe[java]
      - recipe[build-essential]
      - recipe[r-compiledfromsource]
    attributes:
      tz: "Asia/Tokyo"
      r_compiledfromsource:
        sourceurl: "http://stat.ethz.ch/R/daily/R-patched.tar.gz"
