---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  #- name: ubuntu-12.04
  #- name: ubuntu-14.04
  #- name: centos-6.4
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[timezone-ii]
      - recipe[yum]     
      - recipe[java]     
      - recipe[build-essential]
      - recipe[r-compiledfromsource]
    attributes:
      tz: "Asia/Tokyo"
      java:
        install_flavor: "oracle"
        jdk_version: 8
        oracle:
          accept_oracle_download_terms: true
